name: Deploy with serverless

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set working directory
        working-directory: ./
        run: |
          ls -la

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: |
          composer install -n --prefer-dist --optimize-autoloader --no-dev --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Serverless CLI
        run: npm install -g serverless@3.38.0

      - name: Install Serverless Lift
        run: serverless plugin install -n serverless-lift

      - name: Install NPM dependencies
        run: npm install

      - name: Set stage
        run: echo "STAGE=master" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/master'

      - name: Deploy Environment
        run: serverless deploy --stage=$STAGE
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}